<a href="https://colab.research.google.com/github/ozoagujulietoluchi/WTF_submissions/blob/main/ozoagujulietDOConNUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Reading examples on numpy
array = np.array([[4, 2, 8],
              [4, 6, 10]])
array.shape
#This is used to indicate the number of rows and columns present in this given array


(2, 3)

In [ ]:
#Array fundamentals
#Arrays can be put into python sequence such as list. eg
arr = np.array([11, 12, 13, 14, 15, 16])
arr

array([11, 12, 13, 14, 15, 16])

In [ ]:
#The position of the array can be accessed using integer indexing. eg
arr[4]

15

In [ ]:
#like original list, arrays are mutable
arr[3] = 10
arr

array([11, 12, 13, 10, 15, 16])

In [ ]:
#slicing into one dimensional array
arr2 = np.array([3,4,5,6,7,12,23,34,56,78,98])
arr2


array([ 3,  4,  5,  6,  7, 12, 23, 34, 56, 78, 98])

In [ ]:
slicing_intoarray = arr2[3:]
slicing_intoarray

array([ 6,  7, 12, 23, 34, 56, 78, 98])

In [ ]:
slicing_intoarray2 = arr2[-3:]
slicing_intoarray2

array([56, 78, 98])

In [ ]:
#initializing two and  higher dimentional arrays using nested python sequence
array2 =np.array ([[2,4,6,8,10,],[1,3,5,7,9],[11,13,15,17,19]])
array2


array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [ ]:
#using an ndim attribute
array2.ndim

2

In [ ]:
#chacking the shape of the array using this function
array2.shape

(3, 5)

In [ ]:
#checking the size of the array using this function
array2.size

15

In [ ]:
#checking if the result gotten from the size function gives the same output as the product of the result gotten fron shape function
import math
array2.size == math.prod(array2.shape)

True

In [ ]:
#creating an array filled with 0s in three places or in three column usin this function
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#creating an array filled with 1s in four column usin this function
np.ones(4)


array([1., 1., 1., 1.])

In [ ]:
#checking the range of an array using this function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creating an array that its value spaced literally in interval
np.linspace(0, 20, num=6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [ ]:
#arrays are sorted using this function

sor = np.array([1,2,3,4,5,6,12,23,45,7,10,8,9])

np.sort(sor)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 23, 45])

In [ ]:
sor = np.array([1,2,3,4,5,6,12,23,45,7,10,8,9])

np.argsort(sor)

array([ 0,  1,  2,  3,  4,  5,  9, 11, 12, 10,  6,  7,  8])

In [ ]:
sor = np.array([1,2,3,4,5,6,12,23,45,7,10,8,9])

np.lexsort(sor)

0

In [ ]:
#concatenating one dimensional array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,9])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#concatenating two dimensional arrays
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[7,8,9],[12,13,14]])
np.concatenate((c,d))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#reshaoing of an array
ab =np.array ([20,20,30,40])
ab.reshape(2,2)

array([[20, 20],
       [30, 40]])

In [ ]:
#indexing and slicing are done using these functions
able = np.array([2,3,4,5,6,7,8,9,10,13,14,35])
able[2:]
more_index = able
more_index[5:7]

array([7, 8])

In [ ]:
get = np.array([2,3,4,5,6,7,8,9,10,13,14,35])
get[-4:]

array([10, 13, 14, 35])